services:
  mysql:
    image: mysql:latest
    container_name: sql_container 
    environment: 
      MYSQL_ROOT_PASSWORD: password 
      MYSQL_DATABSE: go_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:

